### ISSUE TITLE
VSeeFace macOS release?

### ISSUE THREAD

**Issue by jinfagang** [emilianavt/VSeeFaceSDK#10]
VSeeFace macOS release?

**Comment by emilianavt** [comment]
It's very unlikely as I don't own a Mac. You might be able to run it using wine: https://www.vseeface.icu/#running-on-linux-and-maybe-mac

**Comment by jinfagang** [comment]
@emilianavt Does it open source ? so that I can built on Mac

**Comment by emilianavt** [comment]
It's [not](https://github.com/emilianavt/VSeeFaceReleases/issues/6) Open Source.
