### ISSUE TITLE
Format support outside of Unity.

### ISSUE THREAD

**Issue by techdragon** [emilianavt/VSeeFaceSDK#14]
I know the format is still in development, but is it intended to work outside of Unity at any point in the future? VRM are documented separate of any specific implementation and are based on the open standard GLTF 2.0 file format, while VSFAvatar files are Unity asset bundles which obviously requires Unity. So the only way to ever use this format in its present Unity asset bundle form in any applications other than VSeeFace, would require those applications to be built using Unity. This would make developing native support for VSFAvatar in Blender or Unreal Engine, or any other non Unity 3D graphics software/framework prohibitively difficult if not outright impossible. So is the goal to eventually standardize on a non Unity asset bundle format after you're happy with the feature set?

**Comment by emilianavt** [comment]
There are no plans for that. VSFAvatar is mainly intended as a way of allowing the use of more Unity features and assets by models inside VSeeFace. Even if the format was not asset bundle based, supporting the various Unity assets that can be used in VSFAvatars, such as Magica Cloth and Obi Cloth, outside of Unity seems unlikely.
