### ISSUE TITLE
Strange reference

### ISSUE THREAD

**Issue by Original-Creator** [emilianavt/VSeeFaceSDK#15]
In VSF_Animations.cs it contains this line of code `AssetDatabase.LoadAssetAtPath<AnimationClip>(AssetDatabase.GUIDToAssetPath("3293cdd72fddb9e428a98388947b4697"));` but the guid is never used again.

**Comment by emilianavt** [comment]
It's the T pose animation here:

https://github.com/emilianavt/VSeeFaceSDK/tree/master/VSF%20SDK/Animations

**Comment by Original-Creator** [comment]
Thank you. Its very strange that this doesn't come up in search in any of my editors or even github search.
