### ISSUE TITLE
Unable to Export VSFAvatar from Unity on Linux

### ISSUE THREAD

**Issue by VinTechage** [emilianavt/VSeeFaceSDK#16]
I'm trying to export a VSFAvatar from Unity using the VSF SDK on Linux. However, I get this error every time I try to export a VSFAvatar (Vita included in the SDK).

`FileNotFoundException: /tmp/DefaultCompany/VSF-Sandbox/Vita-Test_1.0.vsfavatar does not exist
System.IO.File.Move (System.String sourceFileName, System.String destFileName) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
VSeeFace.ExportAvatar.ExportAvatarBundle () (at Assets/VSF SDK/Editor/BasicExporter.cs:57)
`
Is there any way to work around this, or make the SDK compatible with Linux in the future? I have having to stick to windows to work with the VSF SDK.

**Comment by emilianavt** [comment]
That's usually just a followup error. The actual error is probably further up.

However, I'm not sure if an export done from the Linux version of the editor could even be loaded. From what I know, the Unity's asset bundles differ in some way between the different platforms, so unless you are somehow building with the build platform set to Windows it may just not work in the end.

**Comment by Sourlemons125** [comment]
how do i upload an avatar from unity need help asap

**Comment by emilianavt** [comment]
You select it and use the export option from the VSF SDK menu.

**Comment by AdalynBlack** [comment]
I was getting the same error and found a fix. The vsfavatar file is created in full lower case. Removing capital letters from the export name results in a successful export
