### ISSUE TITLE
About import issue of VSeeFaceSDK

### ISSUE THREAD

**Issue by tomtomtong** [emilianavt/VSeeFaceSDK#17]
Hello. Would I use the SDK to import VSFAvatar in runtime?

**Comment by emilianavt** [comment]
If you would like to confirm how your exported avatar looks, you can use the VSFAvatarInspector component to runtime import it into the project. However, much of the VSFAvatar functionality only works inside VSeeFace, so for actually testing the avatar, I would still recommend importing it in the actual program.
