### ISSUE TITLE
Combo expressions problem

### ISSUE THREAD

**Issue by katrinshtorm** [emilianavt/VSeeFaceSDK#18]
Hello...When using vrchat there is an ability to blend animations of facial expressions.
I wanted to set facial expressions the same way, so they could blend together when using experimental expression detection. I've recorded a video(link below).
The problem is when I record expressions on Fun/Angry and other they don't combine when I activate 2 expressions. I assume this is because if you set face value in blendshape editor then together with active expression blendshapes, passive nonactive blendshapes is also activated - that's why they don't combine. The same way animation work in vrchat.
Because the method abouve didn't allow me to combine expressions, I decided to try another way.
VSF allows you to use script - VSF_Animations. I've recorded needed animations with ability to combine them and applied script to them. However... in VSeeFace I can't activate animation of face expression. I activate recording key with correct expressions(smile), record, but after I use Calibrate expression - I can't activate it, but it's recorded(if expression is not made with animation but in blendshape editor then it activates correctly). I've recorded a video where I'm trying to record activating animation-expression for Joy.
Also I'm including video where I'm combining facial expressions using  keyboard. With keyboard you can activate multiple type of facial expression, but with Expressions detection you can't

[Combo expressions problem VSeeFace](https://www.youtube.com/watch?v=HdCttXLyaLI)
[Smile Custom Animation(included in vsf_animations script) recording](https://youtu.be/YsJoUHRBIus)
[Combining expressions (using keyboard)](https://youtu.be/cl942hPcOiA)

**Comment by katrinshtorm** [comment]
All my expressions(except body animation) are set to Additive, but blend doesn't happen. In first video(Combo expressions problem) you can see clearly how 1 animations overlap the other

**Comment by emilianavt** [comment]
In the first video, expression detection is used, which cannot possibly detect multiple expressions at the same time due to the way it works.
