### ISSUE TITLE
Are Scripts allowed?

### ISSUE THREAD

**Issue by junebug12851** [emilianavt/VSeeFaceSDK#2]
I want to have my character integrate with Twitch Chat so chat can play with my character but that isn't possible without Scripting. Before I get too deep into this, are scripts allowed? It's not listed anywhere on the README and such so I'm unsure.

**Comment by emilianavt** [comment]
From what I know, scripts cannot be included in Unity asset bundles, so it is not even possible to allow them.

Regarding the Twitch integration, you could take a look at [this video](https://www.youtube.com/watch?v=EV6Xesa8jPA) I recently found. It requires an extra program, but it should at least be possible to trigger blendshapes/animations through it. For some additional control of what is going on in the Unity scene, [this](https://twitter.com/emiliana_vt/status/1381039313501229056) button/animation event based approach may also be useful.

**Comment by junebug12851** [comment]
ah ty! I'll look into them more. They look very complicated ^^ .  ty for the quick response and I'll go from here.
