### ISSUE TITLE
models with particle animations not exporting

### ISSUE THREAD

**Issue by Shinobi-Okami** [emilianavt/VSeeFaceSDK#20]
Unity version: 2019.4.31f1 
VSF version: v1.13.38 
UniVRM version: 0.89.0_9470

**Comment by Shinobi-Okami** [comment]
I got this error: 

 NotImplementedException: The method or operation is not implemented.
UniGLTF.MeshExportInfo..ctor (UnityEngine.Renderer renderer, UniGLTF.GltfExportSettings settings) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportInfo.cs:214)
UniGLTF.MeshExportList.GetInfo (System.Collections.Generic.IEnumerable`1[T] nodes, UniGLTF.GltfExportSettings settings) (at Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportInfo.cs:424)
UniGLTF.MeshExportValidator.SetRoot (UnityEngine.GameObject ExportRoot, UniGLTF.GltfExportSettings settings, UniGLTF.IBlendShapeExportFilter blendShapeFilter) (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MeshExportValidator.cs:40)
VRM.VRMExporterWizard.OnLayout () (at Assets/VRM/Editor/Format/VRMExporterWizard.cs:208)
UniGLTF.ExportDialogBase.BeginGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:103)
UniGLTF.ExportDialogBase.OnGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:80)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.OldOnGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by emilianavt** [comment]
The error looks like you are trying to export the model as a VRM (since it mentions VRMExporterWizard). Particle systems are not supported by VRM. You have to export it using the VSeeFace SDK to VSFAvatar format.
