### ISSUE TITLE
Ok, this is turning special [ EVMC4U ]

### ISSUE THREAD

**Issue by N-NNoThing** [emilianavt/VSeeFaceSDK#22]
Hey its me again, thank you for the tip you give me the other day, i was able to make an entire animation system for a model that i am working on.

I am doing something a little bit weird right now... I'm using a Unity Package to send motion capture from VSeeFace to Unity
https://github.com/gpsnmeajp/EasyVirtualMotionCaptureForUnity

It works really well, all of this Blendshapes weights transmit perfectly to Unity
![image](https://user-images.githubusercontent.com/58456664/180607363-cd39ec9e-df20-4f90-8dde-2b0b869f8bae.png)

But i'm not able to trigger this animations with the VSF_Animations script sadly
![image](https://user-images.githubusercontent.com/58456664/180607446-5bcf141a-a7cb-48ab-a838-1fadff4f6eb4.png)

I'm thinking on learning C# to code a custom script just for Unity to extract the Blendshape weights and injecting them into animators parameters...
I can learn anything, so any tips you tips you give me will be so helpful
Thank you so much again :)

**Comment by emilianavt** [comment]
The animation handling for the VSF_Animations component is handled inside VSeeFace, so it won't work properly inside the Unity editor. You can take a look at the preview function of VSF_Animations for a simplified version of the handling code.
