### ISSUE TITLE
I'm completely lost on how to add a toggle prop using your tutorial

### ISSUE THREAD

**Issue by junebug12851** [emilianavt/VSeeFaceSDK#3]
All Im looking for is a way to toggle a prop on and off manually through a VSeeFace hotkey. In your tutorial [here](https://twitter.com/emiliana_vt/status/1381039313501229056), you explain a complex system involving many levels of components, scripts, animations, and animation controllers that trigger an enable animation which auto-disables after a while.

What I'm looking for is just to enable and disable myself which would probably be a lot simpler.

But you also say
> we just need a simple animation that will enable the "Enabler" object, which can be triggered through the VSF_Animations component.

But all information on this is completely skipped, I don't know what VSF_Animations is or where to go or where to add it, and in the 2 images you share I see an animation "HiddenSphereEnablerOn" but, what is this? It looks different than the rest and all I see is `Enabler: Ga?[1]` but I don't know what that is.

In the other image I see a blendshape called Timedtoggle but I don't know what that is either or where to find or create it, Does IK disabled when active apply to props or is that reccomended for props? What are the blend shapes?

When I go to the next paragraph to help my confusion it's already moved on to VSeeFace. Ive re-read this tutorial for about a week and looked at the 2 images trying to decypher them and I can't figure any of this out. Theres no wiki or help anywhere else and no blogs, forums, or YT tutorials anywhere I could find on VSF SDK. So Im very lost and don't know where or who I'm supposed to ask questions like this too.

**Comment by emilianavt** [comment]
Hi, I already responded to the tweet over there. If you are just trying to toggle a simple prop on and off, you probably don't need the method described in that post. In that case, you can just add the prop as a disabled game object, create a two frame animation that sets it to enabled and add this animation on the VSF_Animations component from the SDK, which allows binding it to an expression hotkey.

For resources about how to use the SDK, you can take a look at [Deat's introduction video](https://www.youtube.com/watch?v=jhQ8DF87I5I) and Suvidriel's [tutorial series](https://www.youtube.com/playlist?list=PLD0oHCcDlFyLzQKwJuw5ptxTWn4sgwvXP). You could also try joining Virtual_Deat's rock platform discord. There's the #vseeface channel and usually people are quite helpful.

**Comment by junebug12851** [comment]
tysm ^^ for the great response and please keep everything going well, good luck with everything ^_^
