### ISSUE TITLE
Animator is not playing an AnimatorController

### ISSUE THREAD

**Issue by VekkaAi** [emilianavt/VSeeFaceSDK#32]
`Animator is not playing an AnimatorController
UnityEngine.Animator:SetFloat (string,single)
VSeeFace.VSF_SetAnimatorFloat:Update () (at Assets/VSF_SDK/VSF_SetAnimatorFloat.cs:28)
`

VSeeFace.VSF_SetAnimatorFloat:Update () (at Assets/VSF_SDK/VSF_SetAnimatorFloat.cs:28)
and int too

why is that?

im sure all set fine.

**Comment by emilianavt** [comment]
It means that the `Animator` you are referencing on the `VSF_SetAnimatorFloat` component doesn't have a runtime animator controller set. Make sure that you are not trying to use the main `Animator` on the model root as VSeeFace uses it.

**Comment by VekkaAi** [comment]
ty for quick reply..!!

it was wrong Animator was selected by Set_Animator..

anyway, i luv your works!!
