### ISSUE TITLE
VseeFace custom blendshape do not enable/disable objects

### ISSUE THREAD

**Issue by Selengiks** [emilianavt/VSeeFaceSDK#35]
Hello. Tried to add some animations to the model, repeated this tutorial (http://yotu.be/p2sdfnypzk).

I created two quad with two animation, add animation controller with bool parameters, and add in it animations, whre one start after another

For switch and transition between it, i add two object with vsf_SetAnimatorBool (or smth that, write from phose so forgot) where i set parameters for controller.

For trigger i created two "trigger" animation, whch only enable "on" object, and disable "off" object, where my vsf_SrtAnimatorBool located. 

So, here is my problem (finnaly): If i set my "trigger" animation in animator, after exporting vsf model nothing is happens!

If i set directly my animations, it will work, but then there is no transition, because it would play only one animation and all.

I upload my video when wake up, or delete issue if find what happened

**Comment by Selengiks** [comment]
Important notice. I tested with enabled preview in vsf_animations, and all my animations work, objects switches, transition done.

So, problem is observing between exported vsf model and VseeFace i think

**Comment by emilianavt2** [comment]
Do make sure that your custom Runtime Animator Controller is not assigned to the main Animator of the model. That Animator is overridden by VSeeFace. You can create a custom one somewhere else though.

**Comment by Selengiks** [comment]
Oh my... Thank you very much) Reset animator in model, and add animator in root, where i paste my controller and trigger animations, readded all animations keys (it missed position because changes full path)? and it now work. So, i see that it's no good, do smth at 5am))

**Comment by Selengiks** [comment]
Also a question. Can i in some way create animation for object, which has two video player for example? I tried to create animation, where i enable one player and disable another - but in animation detects only one of video player

**Comment by emilianavt2** [comment]
Make sure the players are on separate game objects. Unity animations cannot handle more than one component of the same type on the same object.

**Comment by Selengiks** [comment]
Understood, thx u :)
