### ISSUE TITLE
Hands are backwards when exported, crash on exporting with a frozen T-pose

### ISSUE THREAD

**Issue by siliconspecter** [emilianavt/VSeeFaceSDK#39]
I have an avatar which exports correctly using UniVRM - the hand tracking looks great:

![image](https://github.com/emilianavt/VSeeFaceSDK/assets/112014652/17b4f9f9-143c-4bcc-93c7-d6051761fa8f)

If I export the same avatar without making any changes using the VSeeFaceSDK, there is a warning when selecting the avatar from the menu:

![image](https://github.com/emilianavt/VSeeFaceSDK/assets/112014652/f730e3ba-f347-4bdf-8bc9-27c37213a529)
(`Warning: Avatar has non-zero bone rotations.  Make sure to do the first VRM export with "Pose Freeze" Enabled`).

Skipping past this error, it looks good, except that the hands are backwards:

![image](https://github.com/emilianavt/VSeeFaceSDK/assets/112014652/238013d5-f40f-4a0a-895e-badeeecaf4d1)

If I press `Freeze T-Pose` in UniVRM and export that using VSeeFaceSDK, I get a file which crashes VSeeFace:

![image](https://github.com/emilianavt/VSeeFaceSDK/assets/112014652/e51902d4-0ce3-4f05-b0fe-b29f625d4114)

Exporting to VRM and re-importing as the error advises loses all animations unfortunately.

**Comment by emilianavt2** [comment]
> Exporting to VRM and re-importing as the error advises loses all animations unfortunately.

This step is necessary. Without it, it is expected that the armature will behave in very unpredictable ways. You can set up animations etc. again after reimporting.

**Comment by emilianavt2** [comment]
You can try a workflow like this one if you are making many changes: https://www.youtube.com/watch?v=AvI2w5iDCa8

**Comment by siliconspecter** [comment]
Ah I was doing something along the same lines but I’ll give that a go next time.  Thank you!
