### ISSUE TITLE
Sitting down and standing up?

### ISSUE THREAD

**Issue by junebug12851** [emilianavt/VSeeFaceSDK#4]
How would I use the SDK to

* Sit down in a chair
* Stand up from the chair
* have a default arm resting position so the arms aren't clipping through the dress or in general being straight down

I searched Google and this README, I see how to have static and non-static assets and I found a video to permanently sit down and I see information in the README on disabling IK for animations but Im not really getting a good understanding of how to tackle these questions I have completely or if it's even possible.

**Comment by emilianavt** [comment]
This is actually a bit tricky. You could just use sitting and standing animations, but I believe it might not affect the lower body correctly. In this case, ticking the disable IK box would help, but it would also make the model unable to move according to the tracking's movement.

For making the animations themselves, the best way is usually Blender, exporting them as FBX and then importing that into Unity with the rig set to humanoid.

For the default arm rest position, I would recommend just using the arm angle slider in the general settings.

**Comment by junebug12851** [comment]
Sorry im so late responding to this, ty very much for the info and clear explanation
