### ISSUE TITLE
Do blendtrees work for VSF?

### ISSUE THREAD

**Issue by MooshPaw** [emilianavt/VSeeFaceSDK#41]
Just a question rather than an issue, i saw the whitelist of scripts and i see the animator which should be the main component, but i wanted to ask if blendtrees are also whitelisted or are not supported by VSF

**Comment by emilianavt** [comment]
Since I believe that blendtrees are only added within runtime animator controllers, not as regular components, I believe they should work. Note that that avatar's main Animator is always overridden by VSeeFace, but additional Animator components elsewhere can be used freely.

**Comment by MooshPaw** [comment]
Thanks, I decided to kinda debug the blendtree functionality but my guess is that it doesn't actually work

It works fine in unity as you can have anything there and it works just fine, but once exported to vsf it no longer seems to work

I did the same test but with basic transitions rather than blendtree parameters and works that way

**Comment by emilianavt** [comment]
That's good to know. I wonder why it doesn't work though.

**Comment by MooshPaw** [comment]
My guess would be that it needs a specific whitelist, but I don't know much about the unity scripting

**Comment by MooshPaw** [comment]
Ok nevermind everything, after some work i did end up getting the blendtree to work, it's just hard to set up the parameters due to the nature of changing parameters with animations, but it definitely works
