### ISSUE TITLE
Export Failed

### ISSUE THREAD

**Issue by ria00891** [emilianavt/VSeeFaceSDK#42]
I'm suddenly having trouble exporting. didn't change much to the main files. the only things I updated were liltoon and used vrmspringbonetool. I've used liltoon before tho, so maybe vrmspringbonetool did something, not sure. let me know if i need to share anything more

unity version: 2019.4.31f1
univrm: 0.89.0
liltoon: 1.4.0
vsfsdk: 1.13.38c
plugins used: VRMSpringBoneTool(ver 1.6.3)
physics: vrm spring bone
vsf animations/effects/etc: None

error:
![Screenshot_4](https://github.com/emilianavt/VSeeFaceSDK/assets/88756539/ae2a0f7a-ed0c-46c7-bcf8-6ab0de4d87d0)
![Screenshot_6](https://github.com/emilianavt/VSeeFaceSDK/assets/88756539/c214b276-1f25-4e96-8b5c-a0d4895484af)

**Comment by emilianavt** [comment]
Make sure that the avatar you are trying to exporting is based on a reimported VRM file.

**Comment by ria00891** [comment]
> Make sure that the avatar you are trying to exporting is based on a reimported VRM file.

yes, I exported the vrm and reimported. did both dragging in as a new file, replacing the old one directly (I've done this before because it just reloads when being replaced), and starting fresh. still gives same error either way.

**Comment by emilianavt** [comment]
I removing it made it work, that's good. I'm not sure why it would cause the SDK to become unable to find the VRM Meta component though. It doesn't seem like an issue that could be solved by whitelisting something.
