### ISSUE TITLE
Physbones Supported Asset Suggestion

### ISSUE THREAD

**Issue by NyxNymphaea** [emilianavt/VSeeFaceSDK#43]
I would like to suggest that VSeeFaceSDK support the using the VRChat Avatar SDK so that we could have access to Physbones. I currently use Dynamic Bones and MagicaCloth v1 with the VSeeFaceSDK, but that requires avatars that I create for VRChat to be pulled into a separate version of unity and use different components and settings for use within VseeFace. 

As much tweaking as I do, there are things that Dynamic Bones and Magica Cloth cannot mimic and it would be lovely to have access to that.  Also, Physbones within the VRChat Avatar SDK are free, so it would allow for more people to be able to use them without having to buy other unity assets like MagicaCloth or Dynamic Bones. Honestly the movement of Physbones also seems to have more realistic physics, and allowing for posing hair, ears, and tails could be quite handy. 

Currently the unity versions for VSeeFaceSDK and VRChat are the same, so I figured it could be possible.

**Comment by emilianavt** [comment]
I would really like that myself, but sadly the VRChat SDK does not allow its components to be used in other applications.
