### ISSUE TITLE
2019.4.29f1 support?

### ISSUE THREAD

**Issue by JazVega** [emilianavt/VSeeFaceSDK#5]
Hi there,

With VRChat updating to 2019.4.29f1, it's a smidge of a version above the recommended Unity 2019.4.16f1. So far VSFSDK has worked pretty well on the previous 2018.4.20f1 that VRC ran on, but in 2019.4.29f1 it looks like the exports are totally broken (it appears to work but in VSeeFace the avatar is totally empty or invisible). In the interest of keeping all my SDK's for avatar-creation in the same version, I wanna ask if it's possible to see 4.29f1 support for the VRCSDK as well?

Thanks
Jaz

**Comment by emilianavt** [comment]
Hi!

I will look into upgrading Unity. However, if it would break existing vsfavatar files, I may stay with the current version. It'll need some testing.

**Comment by JazVega** [comment]
Wonderful. I'm not sure what causes the breaking, I don't seem to get any error messages in the Unity Log. I don't think it's the VRM component since importing/exporting VRM's work fine. The avatar "loads" without error in VSeeFace, and filesize seems about right, but it just isn't visible. I don't imagine it would be something too massive breaking it given it's not a big version difference, but, that's all the info I can summize from my experiments. Hope to hear more!

**Comment by emilianavt** [comment]
2019.4.29f1 seems to work fine, so I'll release the next version of VSeeFace using that, which should make exports from that version work fine.
