### ISSUE TITLE
Rotation constraints don't work when the constraint source is moved by a dynamic bone script

### ISSUE THREAD

**Issue by Mysteryem** [emilianavt/VSeeFaceSDK#7]
I have a model with two tails. I added a dynamic bone script to move one of the tails and put rotation constraints on the bones in the other tail with the corresponding bone in the first tail as each rotation constraint's only source. In Unity (the VRM that is exported as VSFAvatar) and VRChat (a different version of the same model, but with the same setup), both tails move together, but in VSeeFace the tail with rotation constraints on it doesn't move.

I confirmed that the rotation constraints themselves were working by changing the source in one of them to the model's neck bone and the bone in the tail rotated along with the neck bone as expected in this case.

I did see a mention of VSF_IKFollower and constraints in the README so tried putting VSF_IKFollower on the bones with the rotation constraints, but that had no effect.

I'm using v1.13.36k of both VSeeFace and VSF SDK.

**Comment by emilianavt** [comment]
Thank you for this report. It makes sense that dynamic bones (and other physics scripts) currently override constraints, because they are all executed after constraints are processed. In theory, they could probably be moved to run before constraints, but this may cause other issues. I will look into it.

**Comment by emilianavt** [comment]
I've reordered the player loop so constraints (and particle systems) are executed last. Unless I find any issues, this will be in the next release, which will hopefully be some time during the coming weekend.
