### ISSUE TITLE
Only the first animation for each Blendshape in VSF_Animations is used

### ISSUE THREAD

**Issue by Mysteryem** [emilianavt/VSeeFaceSDK#8]
As my animations have come from VRChat, I have separate animations for bone transforms and blendshapes, I tried adding both of them separately to my "Stars" Blendshape clip in VSF_Animations, but only the first of the two in the list plays when I activate the "Stars" expression in VSeeFace. I swapped their order around to confirm that only the first in the list plays.

I don't know whether this is intentional behaviour or not. Fortunately, these two animations happen to be easy to combine since the length of one is a multiple of the other, but that's not always the case.

I'm using v1.13.36k of both VSeeFace and VSF SDK and Unity 2019.4.29f1.

In case it's relevant, the "Stars" Blendshape clip activates almost all of the same blendshapes as in the FaceStarsInEyes animation, but the animation has an extra blendshape that it animates over time that the "Stars" clip doesn't touch. And the EarExcited animation is only moving non-humanoid bones.

![image](https://user-images.githubusercontent.com/495015/133344072-c5595485-c986-4760-bea1-651fb9e81e08.png)

**Comment by emilianavt** [comment]
Hi, thank you for reporting this!

It's intentional, but the current behaviour where it lets you assign multiple animations, but ignores the extra ones, is confusing. That should be fixed.

**Comment by emilianavt** [comment]
@Deatrathias just added a fix in c73ea0c1a9cc594d1f3b16c5ba48e09cf5027c86. It'll also be in the next SDK release.
